---
## Domain name for the installation
meet_domain: meet.zemon.name

# Mail for let's encrypt certs
le_email: art@zemon.name
# Use debian's certbot
debian_certbot: true
# Auth (none, ldap, token)
xmpp_auth: none
# Allow guest users (when using auth)
allow_guests: true

# token configuration
token_auth_appid: YOUR_APP_ID
token_auth_appsecret: "{{ vault_token_auth_appsecret }}"

## LDAP configuration for saslauthd
saslauthd_ldap_config: |
  ldap_servers: ldap://127.0.0.1/
  ldap_search_base: ou=PEOPLE,dc=YOURDOMAIN,dc=ES
  ldap_filter: (uid=%u)
  ldap_version: 3
  ldap_auth_method: bind

## This shouldn't be necessary,...
## but sometimes download.jitsi.org is not fast enough for apt_key
use_included_jitsi_gpg_key: false

## Recording
enable_recording: false
add_participants_metadata: false
recording_directory: /home/jibri/recs
# Script to execute after recording is finished
recording_processing_script: /dev/null
